WIP - asadiqbal08/Zendesk Theme updates
mitodl/mitxpro-zendesk-theme pull request #1
Opened 2019-06-10 14:31 UTC by asadiqbal08

[TASK 273](https://github.com/mitodl/mitxpro/issues/273)

#### NOTE:
Yet, Following Zendesk theming documentation for better understanding about manifest and its better utilization all over the templates. I will do some more changes in the PR tomorrow. 

![Screenshot_2019-06-10 MITx Pro(1)](https://user-images.githubusercontent.com/7334669/59202330-aa0f9480-8bb5-11e9-94e1-7ee85012153b.png)

@pdpinch FYI over it.

2019-06-10 15:07 UTC, pdpinch commented
I know this is still WIP, but I wanted to point out that the screenshot from 6/10 includes a "community" section and a "recent activity" section that we don't plan to offer. ("Recent activity" may be limited to ZenDesk agents, in which case it's not worth putting in effort to hide).

2019-06-11 08:55 UTC, asadiqbal08 commented
@pdpinch 
- For community section, One can disable it via Help Center, that is the corresponding condition in template. 
```
{{#if help_center.community_enabled}}
```
- For `Recent Activities`, I have disabled it in `manifest.json` file be default for that theme. However, A person can enable it again via visiting admin screen below for that theme. 

![Screen Shot 2019-06-11 at 1 51 41 PM](https://user-images.githubusercontent.com/7334669/59257974-80f01200-8c50-11e9-88b2-de0134d858b1.jpg)

2019-06-11 11:30 UTC, asadiqbal08 commented
@pdpinch I have updated the acceptance criteria + screenshots for #273 above. 
Added details that are the part of this PR.

2019-06-11 11:33 UTC, asadiqbal08 commented on templates/home_page.hbs
> +                {{/is}}
I am thinking for a default image if nothing executed over there.

2019-06-11 12:07 UTC, ahmed-arbisoft requested changes
Primarily SCSS formatting

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    h1 {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    &:before {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    &:after {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +  .contact-block {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +  .copyright {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +        &::before {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +      &:first-child {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +      &::before {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    li {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +  .footer-sub-nav {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    @include desktop {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    @include tablet {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +  .center-content {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +      a {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +      @include tablet {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    li {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    @include tablet {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +  .footer-nav {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    address {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +      @include tablet {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +      @include tablet {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    img {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +    @include tablet {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_footer.scss
> +  .footer-inner {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_header.scss
> +  img {
Newline before block.

2019-06-11 12:07 UTC, ahmed-arbisoft commented on styles/_hero.scss
> +  @include tablet {
Newline before block.

2019-06-11 15:23 UTC, asadiqbal08 commented on manifest.json
> +      "value": ""
@pdpinch any default ones for these empty values, please mention so I can update it here.

2019-06-11 17:28 UTC, pdpinch requested changes
Are the missing defaults meant to be URLs? I gave you some suggestions.

2019-06-11 17:28 UTC, pdpinch commented on manifest.json
> +      "value": ""
```suggestion
      "value": "https://xpro.mit.edu/terms-of-service/"
```

2019-06-11 17:28 UTC, pdpinch commented on manifest.json
> +      "value": ""
```suggestion
      "value": "https://xpro.mit.edu/honor-code/"
```

2019-06-11 17:28 UTC, pdpinch commented on manifest.json
> +      "value": ""
```suggestion
      "value": "https://xpro.mit.edu/privacy-policy/"
```

2019-06-11 17:28 UTC, pdpinch commented on manifest.json
> +      "value": ""
```suggestion
      "value": "https://www.mit.edu/"
```

2019-06-12 08:37 UTC, asadiqbal08 commented
@ahmed-arbisoft @pdpinch are we good to merge  ?

2019-06-12 10:37 UTC, pdpinch approved these changes
I'm good with merging this. 

What happens after that? Can we load update ZenDesk to use this theme instead of the current one (and switch back if necessary)?

2019-06-12 10:45 UTC, ahmed-arbisoft approved these changes

2019-06-12 10:55 UTC, merged